-- ----------------------------------------------------------------------------
--  Apache Derby Table Creation
--
--  @author     Andrei I. Holub
--  @created    August 31, 2006
--  @version    $Id:$
-- ----------------------------------------------------------------------------
 
CREATE TABLE sync_client (
  client_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" VARCHAR(100),
  "version" VARCHAR(50),
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enteredby INT NOT NULL,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedby INT NOT NULL,
  anchor TIMESTAMP DEFAULT NULL,
  enabled CHAR(1) DEFAULT '0',
  code VARCHAR(255)
);

CREATE TABLE sync_system (
  system_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_name VARCHAR(255),
  enabled CHAR(1) DEFAULT '1'
);

CREATE TABLE sync_table (
  table_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  system_id INT NOT NULL REFERENCES sync_system(system_id),
  element_name VARCHAR(255),
  mapped_class_name VARCHAR(255),
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_statement CLOB,
  order_id INT DEFAULT -1,
  sync_item CHAR(1) DEFAULT '0',
  object_key VARCHAR(50)
);

CREATE TABLE sync_map (
  client_id INT NOT NULL REFERENCES sync_client(client_id),
  table_id INT NOT NULL REFERENCES sync_table(table_id),
  record_id INT NOT NULL,
  cuid INT NOT NULL,
  complete CHAR(1) DEFAULT '0',
  status_date TIMESTAMP
);

CREATE UNIQUE INDEX idx_sync_map ON sync_map (client_id, table_id, record_id);

CREATE TABLE sync_conflict_log (
  client_id INT NOT NULL REFERENCES sync_client(client_id),
  table_id INT NOT NULL REFERENCES sync_table(table_id),
  record_id INT NOT NULL,
  status_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sync_log (
  log_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  system_id INT NOT NULL REFERENCES sync_system(system_id),
  client_id INT NOT NULL REFERENCES sync_client(client_id),
  ip VARCHAR(15),
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sync_transaction_log (
  transaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  log_id INT NOT NULL REFERENCES sync_log(log_id),
  reference_id VARCHAR(50),
  element_name VARCHAR(255),
  "action" VARCHAR(20),
  link_item_id INT,
  status_code INT,
  record_count INT,
  "message" CLOB
);

CREATE TABLE process_log (
  process_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  system_id INT NOT NULL REFERENCES sync_system(system_id),
  client_id INT NOT NULL REFERENCES sync_client(client_id),
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  process_name VARCHAR(255),
  process_version VARCHAR(20),
  status INT,
  "message" CLOB
);
