-- ----------------------------------------------------------------------------
--  Apache Derby Table Creation
--
--  @author     Andrei I. Holub
--  @created    August 31, 2006
--  @version    $Id:$
-- ----------------------------------------------------------------------------
 
CREATE TABLE lookup_project_activity (
  code INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  description VARCHAR(50) NOT NULL,
  default_item CHAR(1) DEFAULT '0',
  "level" INTEGER DEFAULT 0,
  enabled CHAR(1) DEFAULT '1',
  group_id INTEGER NOT NULL DEFAULT 0,
  template_id INTEGER DEFAULT 0,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lookup_project_priority (
  code INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  description VARCHAR(50) NOT NULL,
  default_item CHAR(1) DEFAULT '0',
  "level" INTEGER DEFAULT 0,
  enabled CHAR(1) DEFAULT '1',
  group_id INTEGER NOT NULL DEFAULT 0,
  graphic VARCHAR(75),
  "type" INTEGER NOT NULL,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lookup_project_status (
  code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR(50) NOT NULL,
  default_item CHAR(1) DEFAULT '0',
  "level" INTEGER DEFAULT 0,
  enabled CHAR(1) DEFAULT '1',
  group_id INTEGER NOT NULL DEFAULT 0,
  graphic VARCHAR(75),
  "type" INTEGER NOT NULL,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lookup_project_loe (
  code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR(50) NOT NULL,
  base_value INTEGER DEFAULT 0 NOT NULL,
  default_item CHAR(1) DEFAULT '0',
  "level" INTEGER DEFAULT 0,
  enabled CHAR(1) DEFAULT '1',
  group_id INTEGER NOT NULL DEFAULT 0,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lookup_project_role (
  code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR(50) NOT NULL,
  default_item CHAR(1) DEFAULT '0',
  "level" INTEGER DEFAULT 0,
  enabled CHAR(1) DEFAULT '1',
  group_id INTEGER NOT NULL DEFAULT 0,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lookup_project_category (
  code INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  description VARCHAR(80) NOT NULL,
  default_item CHAR(1) DEFAULT '0',
  "level" INTEGER DEFAULT 0,
  enabled CHAR(1) DEFAULT '1',
  group_id INTEGER NOT NULL DEFAULT 0,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lookup_news_template (
  code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR(255) NOT NULL,
  default_item CHAR(1) DEFAULT '0',
  "level" INTEGER DEFAULT 0,
  enabled CHAR(1) DEFAULT '1',
  group_id INTEGER NOT NULL DEFAULT 0,
  load_article CHAR(1) DEFAULT '0',
  load_project_article_list CHAR(1) DEFAULT '0',
  load_article_linked_list CHAR(1) DEFAULT '0',
  load_public_projects CHAR(1) DEFAULT '0',
  load_article_category_list CHAR(1) DEFAULT '0',
  mapped_jsp VARCHAR(255) NOT NULL,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE projects (
  project_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id INTEGER DEFAULT NULL,
  department_id INTEGER REFERENCES lookup_department(code),
  template_id INTEGER,
  title VARCHAR(100) NOT NULL ,
  shortDescription VARCHAR(200) NOT NULL ,
  requestedBy VARCHAR(50) DEFAULT NULL,
  requestedDept VARCHAR(50) DEFAULT NULL,
  requestDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  approvalDate TIMESTAMP,
  closeDate TIMESTAMP,
  owner INTEGER DEFAULT NULL,
  entered TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  enteredBy INTEGER NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modifiedBy INTEGER NOT NULL REFERENCES "access"(user_id),
  approvalBy INTEGER DEFAULT NULL REFERENCES "access"(user_id),
  category_id INTEGER DEFAULT NULL REFERENCES lookup_project_category(code),
  portal CHAR(1) NOT NULL DEFAULT '0',
  allow_guests CHAR(1) NOT NULL DEFAULT '0',
  news_enabled CHAR(1) NOT NULL DEFAULT '1',
  details_enabled CHAR(1) NOT NULL DEFAULT '1',
  team_enabled CHAR(1) NOT NULL DEFAULT '1',
  plan_enabled CHAR(1) NOT NULL DEFAULT '1',
  lists_enabled CHAR(1) NOT NULL DEFAULT '1',
  discussion_enabled CHAR(1) NOT NULL DEFAULT '1',
  tickets_enabled CHAR(1) NOT NULL DEFAULT '1',
  documents_enabled CHAR(1) NOT NULL DEFAULT '1',
  news_label VARCHAR(50) DEFAULT NULL,
  details_label VARCHAR(50) DEFAULT NULL,
  team_label VARCHAR(50) DEFAULT NULL,
  plan_label VARCHAR(50) DEFAULT NULL,
  lists_label VARCHAR(50) DEFAULT NULL,
  discussion_label VARCHAR(50) DEFAULT NULL,
  tickets_label VARCHAR(50) DEFAULT NULL,
  documents_label VARCHAR(50) DEFAULT NULL,
  est_closedate TIMESTAMP,
  budget FLOAT,
  budget_currency VARCHAR(5),
  requestDate_timezone VARCHAR(255),
  est_closedate_timezone VARCHAR(255),
  portal_default CHAR(1) NOT NULL DEFAULT '0',
  portal_header VARCHAR(255),
  portal_format VARCHAR(255),
  portal_key VARCHAR(255),
  portal_build_news_body CHAR(1) NOT NULL DEFAULT '0',
  portal_news_menu CHAR(1) NOT NULL DEFAULT '0',
  description CLOB,
  allows_user_observers CHAR(1) NOT NULL DEFAULT '0',
  "level" INTEGER NOT NULL DEFAULT 10,
  portal_page_type INTEGER,
  calendar_enabled CHAR(1) NOT NULL DEFAULT '1',
  calendar_label VARCHAR(50) DEFAULT NULL,
  accounts_enabled CHAR(1) NOT NULL DEFAULT '1',
  accounts_label VARCHAR(50) DEFAULT NULL,
  trashed_date TIMESTAMP
);

CREATE INDEX projects_idx
  ON projects
  (group_id, project_id);

CREATE TABLE project_requirements (
  requirement_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(project_id),
  submittedBy VARCHAR(50) ,
  departmentBy VARCHAR(30) ,
  shortDescription VARCHAR(255) NOT NULL,
  description CLOB NOT NULL,
  dateReceived TIMESTAMP ,
  estimated_loevalue INTEGER ,
  estimated_loetype INTEGER REFERENCES lookup_project_loe,
  actual_loevalue INTEGER ,
  actual_loetype INTEGER REFERENCES lookup_project_loe,
  deadline TIMESTAMP ,
  approvedBy INTEGER REFERENCES "access"(user_id),
  approvalDate TIMESTAMP ,
  closedBy INTEGER REFERENCES "access"(user_id),
  closeDate TIMESTAMP ,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enteredBy INTEGER NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedBy INTEGER NOT NULL REFERENCES "access"(user_id),
  startdate TIMESTAMP ,
  startdate_timezone VARCHAR(255),
  deadline_timezone VARCHAR(255),
  due_date_timezone VARCHAR(255)
);

CREATE TABLE project_assignments_folder (
  folder_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  parent_id INTEGER DEFAULT NULL REFERENCES project_assignments_folder(folder_id),
  requirement_id INTEGER NOT NULL REFERENCES project_requirements(requirement_id),
  name VARCHAR(255) NOT NULL,
  description CLOB ,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enteredBy INTEGER NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedBy INTEGER NOT NULL REFERENCES "access"(user_id)
);

CREATE TABLE project_assignments (
  assignment_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(project_id),
  requirement_id INTEGER DEFAULT NULL REFERENCES project_requirements(requirement_id),
  assignedBy INTEGER REFERENCES "access"(user_id),
  user_assign_id INTEGER DEFAULT NULL REFERENCES "access"(user_id),
  technology VARCHAR(50) ,
  "role" VARCHAR(255) ,
  estimated_loevalue INTEGER ,
  estimated_loetype INTEGER REFERENCES lookup_project_loe,
  actual_loevalue INTEGER ,
  actual_loetype INTEGER REFERENCES lookup_project_loe,
  priority_id INTEGER REFERENCES lookup_project_priority,
  assign_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  est_start_date TIMESTAMP ,
  start_date TIMESTAMP ,
  due_date TIMESTAMP ,
  status_id INTEGER REFERENCES lookup_project_status,
  status_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  complete_date TIMESTAMP ,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enteredBy INTEGER NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedBy INTEGER NOT NULL REFERENCES "access"(user_id),
  folder_id INTEGER REFERENCES project_assignments_folder(folder_id),
  percent_complete INTEGER ,
  due_date_timezone VARCHAR(255)
);
  
CREATE INDEX project_assignments_cidx ON project_assignments 
  (complete_date, user_assign_id);
  
CREATE INDEX proj_assign_req_id_idx ON project_assignments (requirement_id);
  
CREATE TABLE project_assignments_status (
  status_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  assignment_id INTEGER NOT NULL REFERENCES project_assignments,
  user_id INTEGER NOT NULL REFERENCES "access"(user_id),
  description CLOB NOT NULL,
  status_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  percent_complete INTEGER ,
  project_status_id INTEGER REFERENCES lookup_project_status,
  user_assign_id INTEGER  REFERENCES "access"(user_id)
);


CREATE TABLE project_issues_categories (
  category_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(project_id),
  subject VARCHAR(255) NOT NULL,
  description CLOB DEFAULT NULL,
  enabled CHAR(1) NOT NULL DEFAULT '1',
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enteredBy INTEGER NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedBy INTEGER NOT NULL REFERENCES "access"(user_id),
  topics_count INTEGER NOT NULL DEFAULT 0,
  posts_count INTEGER NOT NULL DEFAULT 0,
  last_post_date TIMESTAMP,
  last_post_by INTEGER,
  allow_files CHAR(1) NOT NULL DEFAULT '0'
);

CREATE TABLE project_issues (
  issue_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(project_id),
  subject VARCHAR(255) NOT NULL,
  "message" CLOB NOT NULL,
  importance INTEGER DEFAULT 0,
  enabled CHAR(1) DEFAULT '1',
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enteredBy INTEGER NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedBy INTEGER NOT NULL REFERENCES "access"(user_id),
  category_id INTEGER DEFAULT NULL REFERENCES project_issues_categories(category_id),
  reply_count INTEGER NOT NULL DEFAULT 0,
  last_reply_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_reply_by INTEGER
);
  
CREATE TABLE project_issue_replies (
  reply_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  issue_id INTEGER NOT NULL REFERENCES project_issues,
  reply_to INTEGER DEFAULT 0 ,
  subject VARCHAR(255) NOT NULL ,
  "message" CLOB NOT NULL ,
  importance INTEGER DEFAULT NULL,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enteredBy INTEGER NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedBy INTEGER NOT NULL REFERENCES "access"(user_id)
);

CREATE TABLE project_folders (
  folder_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link_module_id INTEGER NOT NULL,
  link_item_id INTEGER NOT NULL,
  subject VARCHAR(255) NOT NULL,
  description CLOB,
  parent_id INT DEFAULT NULL,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enteredBy INTEGER NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedBy INTEGER NOT NULL REFERENCES "access"(user_id),
  "display" INTEGER DEFAULT NULL
);
  
CREATE TABLE project_files (
  item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
  link_module_id INTEGER NOT NULL,
  link_item_id INTEGER NOT NULL,
  folder_id INTEGER REFERENCES project_folders,
  client_filename VARCHAR(255) NOT NULL,
  filename VARCHAR(255) NOT NULL,
  subject VARCHAR(500) NOT NULL ,
  "size" INTEGER DEFAULT 0 ,
  "version" FLOAT DEFAULT 0 , 
  enabled CHAR(1) DEFAULT '1' ,
  downloads INTEGER DEFAULT 0,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enteredBy INTEGER NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedBy INTEGER NOT NULL REFERENCES "access"(user_id),
  default_file CHAR(1) DEFAULT '0',
  allow_portal_access CHAR(1) DEFAULT '0'
);

CREATE INDEX project_files_cidx ON project_files 
  (link_module_id, link_item_id);

CREATE TABLE project_files_version (
  version_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY ,                                 
  item_id INTEGER REFERENCES project_files(item_id),
  client_filename VARCHAR(255) NOT NULL,
  filename VARCHAR(255) NOT NULL,
  subject VARCHAR(500) NOT NULL ,
  "size" INTEGER DEFAULT 0 ,
  "version" FLOAT DEFAULT 0 ,
  enabled CHAR(1) DEFAULT '1' ,
  downloads INTEGER DEFAULT 0,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enteredBy INTEGER NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedBy INTEGER NOT NULL REFERENCES "access"(user_id),
  allow_portal_access CHAR(1) DEFAULT '0'
);

CREATE TABLE project_files_download (
  download_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY ,                                    
  item_id INTEGER NOT NULL REFERENCES project_files(item_id),
  "version" FLOAT DEFAULT 0 ,
  user_download_id INTEGER DEFAULT NULL REFERENCES "access"(user_id),
  download_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE project_files_thumbnail (
  item_id INTEGER REFERENCES project_files(item_id),
  filename VARCHAR(255) NOT NULL,
  "size" INTEGER DEFAULT 0 ,
  "version" FLOAT DEFAULT 0 ,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enteredBy INTEGER NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedBy INTEGER NOT NULL REFERENCES "access"(user_id)
);


CREATE TABLE project_team (
  project_id INTEGER NOT NULL REFERENCES projects(project_id),
  user_id INTEGER NOT NULL REFERENCES "access"(user_id),
  userlevel INTEGER NOT NULL REFERENCES lookup_project_role(code),
  entered TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  enteredby INTEGER NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modifiedby INTEGER NOT NULL REFERENCES "access"(user_id),
  status INTEGER DEFAULT NULL,
  last_accessed TIMESTAMP,
  role_type INTEGER
);
CREATE UNIQUE INDEX project_team_uni_idx ON project_team (project_id, user_id);

CREATE TABLE project_news_category (
  category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(project_id),
  category_name VARCHAR(255),
  entered TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "level" INTEGER NOT NULL DEFAULT 0,
  enabled CHAR(1) DEFAULT '1'
);

CREATE TABLE project_news (
  news_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(project_id),
  category_id INTEGER DEFAULT NULL REFERENCES project_news_category(category_id),
  subject VARCHAR(255) NOT NULL,
  intro CLOB DEFAULT NULL,
  "message" CLOB,
  entered TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  enteredby INTEGER NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modifiedby INTEGER NOT NULL REFERENCES "access"(user_id),
  start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  end_date TIMESTAMP DEFAULT NULL,
  allow_replies CHAR(1) DEFAULT '0',
  allow_rating CHAR(1) DEFAULT '0',
  rating_count INTEGER NOT NULL DEFAULT 0,
  avg_rating FLOAT DEFAULT 0,
  priority_id INTEGER DEFAULT 10,
  read_count INTEGER NOT NULL DEFAULT 0,
  enabled CHAR(1) DEFAULT '1',
  status INTEGER DEFAULT NULL,
  html CHAR(1) NOT NULL DEFAULT '1',
  start_date_timezone VARCHAR(255),
  end_date_timezone VARCHAR(255),
  classification_id INTEGER NOT NULL,
  template_id INTEGER REFERENCES lookup_news_template
);

CREATE TABLE project_requirements_map (
  map_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects,
  requirement_id INTEGER NOT NULL REFERENCES project_requirements,
  "position" INTEGER NOT NULL,
  indent INTEGER NOT NULL DEFAULT 0,
  folder_id INTEGER DEFAULT NULL REFERENCES project_assignments_folder,
  assignment_id INTEGER DEFAULT NULL REFERENCES project_assignments
);

CREATE INDEX proj_req_map_pr_req_pos_idx ON project_requirements_map (project_id, requirement_id, "position");

CREATE TABLE lookup_project_permission_category (
  code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR(300) NOT NULL,
  default_item CHAR(1) DEFAULT '0',
  "level" INTEGER DEFAULT 0,
  enabled CHAR(1) DEFAULT '1',
  group_id INTEGER NOT NULL DEFAULT 0,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lookup_project_permission (
  code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id INTEGER REFERENCES lookup_project_permission_category(code),
  permission VARCHAR(300) UNIQUE NOT NULL,
  description VARCHAR(300) NOT NULL,
  default_item CHAR(1) DEFAULT '0',
  "level" INTEGER DEFAULT 0,
  enabled CHAR(1) DEFAULT '1',
  group_id INTEGER NOT NULL DEFAULT 0,
  default_role INTEGER REFERENCES lookup_project_role(code),
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE project_permissions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(project_id),
  permission_id INTEGER NOT NULL REFERENCES lookup_project_permission(code),
  userlevel INTEGER NOT NULL REFERENCES lookup_project_role(code)
);

CREATE TABLE project_accounts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(project_id),
  org_id INTEGER NOT NULL REFERENCES organization(org_id),
  entered TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX proj_acct_project_idx ON project_accounts (project_id);
CREATE INDEX proj_acct_org_idx ON project_accounts (org_id);

