-- ----------------------------------------------------------------------------
--  Apache Derby Table Creation
--
--  @author     Andrei I. Holub
--  @created    August 31, 2006
--  @version    $Id:$
-- ----------------------------------------------------------------------------
 
CREATE TABLE lookup_asset_status(
 code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 description VARCHAR(300),
 default_item CHAR(1) DEFAULT '0',
 "level" INTEGER,
 enabled CHAR(1) DEFAULT '1'
);

CREATE TABLE lookup_sc_category(
 code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 description VARCHAR(300),
 default_item CHAR(1) DEFAULT '0',
 "level" INTEGER,
 enabled CHAR(1) DEFAULT '1'
);

CREATE TABLE lookup_sc_type(
 code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 description VARCHAR(300),
 default_item CHAR(1) DEFAULT '0',
 "level" INTEGER,
 enabled CHAR(1) DEFAULT '1'
);

CREATE TABLE lookup_response_model(
 code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 description VARCHAR(300),
 default_item CHAR(1) DEFAULT '0',
 "level" INTEGER,
 enabled CHAR(1) DEFAULT '1'
);

CREATE TABLE lookup_phone_model(
 code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 description VARCHAR(300),
 default_item CHAR(1) DEFAULT '0',
 "level" INTEGER,
 enabled CHAR(1) DEFAULT '1'
);

CREATE TABLE lookup_onsite_model(
 code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 description VARCHAR(300),
 default_item CHAR(1) DEFAULT '0',
 "level" INTEGER,
 enabled CHAR(1) DEFAULT '1'
);

CREATE TABLE lookup_email_model(
 code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 description VARCHAR(300),
 default_item CHAR(1) DEFAULT '0',
 "level" INTEGER,
 enabled CHAR(1) DEFAULT '1'
);

CREATE TABLE lookup_hours_reason(
 code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 description VARCHAR(300),
 default_item CHAR(1) DEFAULT '0',
 "level" INTEGER,
 enabled CHAR(1) DEFAULT '1'
);

CREATE TABLE lookup_asset_manufacturer(
 code INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
 description VARCHAR(300),
 default_item CHAR(1) DEFAULT '0',
 "level" INTEGER,
 enabled CHAR(1) DEFAULT '1'
);

CREATE TABLE lookup_asset_vendor(
 code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 description VARCHAR(300),
 default_item CHAR(1) DEFAULT '0',
 "level" INTEGER,
 enabled CHAR(1) DEFAULT '1'
);

CREATE TABLE service_contract (
  contract_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_number VARCHAR(30),
  account_id INT NOT NULL REFERENCES organization(org_id),
  initial_start_date TIMESTAMP NOT NULL,
  current_start_date TIMESTAMP,
  current_end_date TIMESTAMP,
  category INT REFERENCES lookup_sc_category(code),
  "type" INT REFERENCES lookup_sc_type(code),
  contact_id INT REFERENCES contact(contact_id),
  description CLOB,
  contract_billing_notes CLOB,
  response_time INT REFERENCES lookup_response_model(code),
  telephone_service_model INT REFERENCES lookup_phone_model(code),
  onsite_service_model INT REFERENCES lookup_onsite_model(code),
  email_service_model INT REFERENCES lookup_email_model(code),
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enteredby INT NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedby INT NOT NULL REFERENCES "access"(user_id),
  enabled CHAR(1) DEFAULT '1',
  contract_value FLOAT,
  total_hours_remaining FLOAT,
  service_model_notes CLOB,
  initial_start_date_timezone VARCHAR(255),
  current_start_date_timezone VARCHAR(255),
  current_end_date_timezone VARCHAR(255),
  trashed_date TIMESTAMP
  );

CREATE TABLE service_contract_hours (
  history_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link_contract_id INT REFERENCES service_contract(contract_id),
  adjustment_hours FLOAT,
  adjustment_reason INT REFERENCES lookup_hours_reason(code),
  adjustment_notes CLOB,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enteredby INT NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedby INT NOT NULL REFERENCES "access"(user_id)
);

CREATE TABLE service_contract_products(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link_contract_id INT REFERENCES service_contract(contract_id),
  link_product_id INT REFERENCES product_catalog(product_id)
);

CREATE TABLE asset_category ( 
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cat_level int NOT NULL DEFAULT 0,
  parent_cat_code int NOT NULL DEFAULT 0,
  description VARCHAR(300) NOT NULL,
  full_description CLOB NOT NULL DEFAULT '',
  default_item CHAR(1) DEFAULT '0',
  "level" INTEGER DEFAULT 0,
  enabled CHAR(1) DEFAULT '1',
  site_id INTEGER REFERENCES lookup_site_id(code)
);

CREATE TABLE asset_category_draft (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link_id INT DEFAULT -1,
  cat_level int NOT NULL DEFAULT 0,
  parent_cat_code int NOT NULL DEFAULT 0,
  description VARCHAR(300) NOT NULL,
  full_description CLOB NOT NULL DEFAULT '',
  default_item CHAR(1) DEFAULT '0',
  "level" INTEGER DEFAULT 0,
  enabled CHAR(1) DEFAULT '1',
  site_id INTEGER REFERENCES lookup_site_id(code)
);

CREATE TABLE asset (
  asset_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INT REFERENCES organization(org_id),
  contract_id INT REFERENCES service_contract(contract_id),
  date_listed TIMESTAMP,
  asset_tag VARCHAR(30),
  status INT,
  location VARCHAR(256),
  level1 INT REFERENCES asset_category(id),
  level2 INT REFERENCES asset_category(id),
  level3 INT REFERENCES asset_category(id),
  serial_number VARCHAR(30),
  model_version VARCHAR(30),
  description CLOB,
  expiration_date TIMESTAMP,
  inclusions CLOB,
  exclusions CLOB,
  purchase_date TIMESTAMP,
  po_number VARCHAR(30),
  purchased_from VARCHAR(30),
  contact_id INT REFERENCES contact(contact_id),
  notes CLOB,
  response_time INT REFERENCES lookup_response_model(code),
  telephone_service_model INT REFERENCES lookup_phone_model(code),
  onsite_service_model INT REFERENCES lookup_onsite_model(code),
  email_service_model INT REFERENCES lookup_email_model(code),
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enteredby INT NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedby INT NOT NULL REFERENCES "access"(user_id),
  enabled CHAR(1) DEFAULT '1',
  purchase_cost FLOAT,
  date_listed_timezone VARCHAR(255),
  expiration_date_timezone VARCHAR(255),
  purchase_date_timezone VARCHAR(255),
  trashed_date TIMESTAMP,
  parent_id INTEGER REFERENCES asset(asset_id),
  vendor_code INT REFERENCES lookup_asset_vendor(code),
  manufacturer_code INT REFERENCES lookup_asset_manufacturer(code)
);

CREATE TABLE lookup_asset_materials(
 code INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 description VARCHAR(300),
 default_item CHAR(1) DEFAULT '0',
 "level" INTEGER,
 enabled CHAR(1) DEFAULT '1'
);

CREATE TABLE asset_materials_map (
  map_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_id INTEGER NOT NULL REFERENCES asset(asset_id),
  code INTEGER NOT NULL REFERENCES lookup_asset_materials(code),
  quantity FLOAT,
  entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

