
INSERT INTO autoguide_options (option_name) VALUES ('A/T');
INSERT INTO autoguide_options (option_name) VALUES ('4-CYL');
INSERT INTO autoguide_options (option_name) VALUES ('6-CYL');
INSERT INTO autoguide_options (option_name) VALUES ('V-8');
INSERT INTO autoguide_options (option_name) VALUES ('CRUISE');
INSERT INTO autoguide_options (option_name) VALUES ('5-SPD');
INSERT INTO autoguide_options (option_name) VALUES ('4X4');
INSERT INTO autoguide_options (option_name) VALUES ('2-DOOR');
INSERT INTO autoguide_options (option_name) VALUES ('4-DOOR');
INSERT INTO autoguide_options (option_name) VALUES ('LEATHER');
INSERT INTO autoguide_options (option_name) VALUES ('P/DL');
INSERT INTO autoguide_options (option_name) VALUES ('T/W');
INSERT INTO autoguide_options (option_name) VALUES ('P/SEATS');
INSERT INTO autoguide_options (option_name) VALUES ('P/WIND');
INSERT INTO autoguide_options (option_name) VALUES ('P/S');
INSERT INTO autoguide_options (option_name) VALUES ('BEDLINE');
INSERT INTO autoguide_options (option_name) VALUES ('LOW MILES');
INSERT INTO autoguide_options (option_name) VALUES ('EX CLEAN');
INSERT INTO autoguide_options (option_name) VALUES ('LOADED');
INSERT INTO autoguide_options (option_name) VALUES ('A/C');
INSERT INTO autoguide_options (option_name) VALUES ('SUNROOF');
INSERT INTO autoguide_options (option_name) VALUES ('AM/FM ST');
INSERT INTO autoguide_options (option_name) VALUES ('CD PLYR');
INSERT INTO autoguide_options (option_name) VALUES ('ABS');
INSERT INTO autoguide_options (option_name) VALUES ('ALARM');
INSERT INTO autoguide_options (option_name) VALUES ('SLD R. WIN');
INSERT INTO autoguide_options (option_name) VALUES ('AIRBAG');
INSERT INTO autoguide_options (option_name) VALUES ('1 OWNER');
INSERT INTO autoguide_options (option_name) VALUES ('ALLOY WH');

