DELETE FROM state;
INSERT INTO state VALUES('AK','Alaska');
INSERT INTO state VALUES('AL','Alabama');
INSERT INTO state VALUES('AR','Arkansas');
INSERT INTO state VALUES('AZ','Arizona');
INSERT INTO state VALUES('CA','California');
INSERT INTO state VALUES('CO','Colorado');
INSERT INTO state VALUES('CT','Connecticut');
INSERT INTO state VALUES('DE','Delaware');
INSERT INTO state VALUES('FL','Florida');
INSERT INTO state VALUES('GA','Georgia');
INSERT INTO state VALUES('HI','Hawaii');
INSERT INTO state VALUES('ID','Idaho');
INSERT INTO state VALUES('IL','Illinois');
INSERT INTO state VALUES('IN','Indiana');
INSERT INTO state VALUES('KS','Kansas');
INSERT INTO state VALUES('KY','Kentucky');
INSERT INTO state VALUES('LA','Louisiana');
INSERT INTO state VALUES('ME','Maine');
INSERT INTO state VALUES('MD','Maryland');
INSERT INTO state VALUES('MA','Massachusetts');
INSERT INTO state VALUES('MI','Michigan');
INSERT INTO state VALUES('MN','Minnesota');
INSERT INTO state VALUES('MS','Mississippi');
INSERT INTO state VALUES('MO','Mossouri');
INSERT INTO state VALUES('MT','Montana');
INSERT INTO state VALUES('NE','Nebraska');
INSERT INTO state VALUES('NV','Nevada');
INSERT INTO state VALUES('NH','New Hampshire');
INSERT INTO state VALUES('NJ','New Jersey');
INSERT INTO state VALUES('NM','New Mexico');
INSERT INTO state VALUES('NY','New York');
INSERT INTO state VALUES('NC','North Carolina');
INSERT INTO state VALUES('ND','North Dakota');
INSERT INTO state VALUES('OH','Ohio');
INSERT INTO state VALUES('OK','Oklahoma');
INSERT INTO state VALUES('OR','Oregon');
INSERT INTO state VALUES('PA','Pennsylvania');
INSERT INTO state VALUES('RI','Rhode Island');
INSERT INTO state VALUES('SC','South Carolina');
INSERT INTO state VALUES('SD','South Dakota');
INSERT INTO state VALUES('TN','Tennessee');
INSERT INTO state VALUES('TX','Texas');
INSERT INTO state VALUES('UT','Utah');
INSERT INTO state VALUES('VA','Virginia');
INSERT INTO state VALUES('VT','Vermont');
INSERT INTO state VALUES('WA','Washington');
INSERT INTO state VALUES('DC','Washington D.C.');
INSERT INTO state VALUES('WI','Wisconsin');
INSERT INTO state VALUES('WV','West Virginia');
INSERT INTO state VALUES('WY','Wyoming');

