CREATE SEQUENCE netapp_contra_xpiration_id_seq;
CREATE TABLE netapp_contractexpiration(
  expiration_id INT NOT NULL PRIMARY KEY,
  serial_number NVARCHAR2(255),
  agreement_number NVARCHAR2(255),
  services NVARCHAR2(1024),
  startdate TIMESTAMP,
  enddate TIMESTAMP,
  installed_at_company_name NVARCHAR2(1024),
  installed_at_site_name NVARCHAR2(1024),
  group_name NVARCHAR2(255),
  product_number NVARCHAR2(255),
  system_name NVARCHAR2(255),
  operating_system NVARCHAR2(255),
  no_of_shelves INT,
  no_of_disks INT,
  nvram INT,
  memory INT,
  auto_support_status NVARCHAR2(255),
  installed_at_address NVARCHAR2(1024),
  city NVARCHAR2(255),
  state_province NVARCHAR2(255),
  postal_code NVARCHAR2(255),
  country NVARCHAR2(255),
  installed_at_contact_firstname NVARCHAR2(255),
  contact_lastname NVARCHAR2(255),
  contact_email NVARCHAR2(255),
  agreement_company NVARCHAR2(255),
  quote_amount FLOAT,
  quotegenerateddate TIMESTAMP,
  quoteaccepteddate TIMESTAMP,
  quoterejecteddate TIMESTAMP,
  "comment" CLOB,
  import_id INT,
  status_id INT,
  entered TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  enteredBy INT NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  modifiedBy INT NOT NULL REFERENCES "access"(user_id)
);

CREATE SEQUENCE netapp_contra_ation_log_id_seq;
CREATE TABLE netapp_contractexpiration_log(
  id INT NOT NULL PRIMARY KEY,
  expiration_id INT REFERENCES netapp_contractexpiration(expiration_id),
  quote_amount FLOAT,
  quotegenerateddate TIMESTAMP,
  quoteaccepteddate TIMESTAMP,
  quoterejecteddate TIMESTAMP,
  "comment" CLOB,
  entered TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  enteredBy INT NOT NULL REFERENCES "access"(user_id),
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  modifiedBy INT NOT NULL REFERENCES "access"(user_id)
);
